--
-- PostgreSQL database dump
--

\restrict 2716qWRxioBolQu3E3gTMSm0kBzjLiRhWXfOmbPHBjnYUcT2ilzW9OLEleXLZNl

-- Dumped from database version 18.3
-- Dumped by pg_dump version 18.3

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET transaction_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

SET default_tablespace = '';

SET default_table_access_method = heap;

--
-- Name: badges; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.badges (
    id bigint NOT NULL,
    awarded_at timestamp(6) without time zone,
    checkin_count integer NOT NULL,
    week_end date NOT NULL,
    week_start date NOT NULL,
    circle_id bigint NOT NULL,
    user_id bigint NOT NULL
);


--
-- Name: badges_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.badges ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.badges_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: checkins; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.checkins (
    id bigint NOT NULL,
    checkin_date date NOT NULL,
    completed boolean NOT NULL,
    created_at timestamp(6) without time zone,
    circle_id bigint NOT NULL,
    user_id bigint NOT NULL
);


--
-- Name: checkins_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.checkins ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.checkins_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: circle_members; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.circle_members (
    id bigint NOT NULL,
    joined_at timestamp(6) without time zone,
    circle_id bigint NOT NULL,
    user_id bigint NOT NULL
);


--
-- Name: circle_members_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.circle_members ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.circle_members_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: circle_tasks; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.circle_tasks (
    id bigint NOT NULL,
    created_at timestamp(6) without time zone,
    display_order integer,
    title character varying(255) NOT NULL,
    circle_id bigint NOT NULL,
    user_id bigint NOT NULL
);


--
-- Name: circle_tasks_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.circle_tasks ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.circle_tasks_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: circles; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.circles (
    id bigint NOT NULL,
    created_at timestamp(6) without time zone,
    invite_code character varying(255),
    name character varying(255) NOT NULL,
    created_by bigint NOT NULL,
    custom_threshold_percent integer,
    completion_threshold character varying(255) DEFAULT 'ANY_TASK'::character varying NOT NULL,
    status character varying(255) DEFAULT 'ACTIVE'::character varying NOT NULL
);


--
-- Name: circles_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.circles ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.circles_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: email_verification_tokens; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.email_verification_tokens (
    id bigint NOT NULL,
    email character varying(255) NOT NULL,
    expires_at timestamp(6) without time zone NOT NULL,
    token character varying(255) NOT NULL,
    used boolean NOT NULL
);


--
-- Name: email_verification_tokens_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.email_verification_tokens ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.email_verification_tokens_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: goals; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.goals (
    id bigint NOT NULL,
    category character varying(255) NOT NULL,
    created_at timestamp(6) without time zone,
    description character varying(255),
    end_date date NOT NULL,
    start_date date NOT NULL,
    title character varying(255) NOT NULL,
    circle_id bigint NOT NULL
);


--
-- Name: goals_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.goals ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.goals_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: password_reset_tokens; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.password_reset_tokens (
    id bigint NOT NULL,
    email character varying(255) NOT NULL,
    expires_at timestamp(6) without time zone NOT NULL,
    token character varying(255) NOT NULL,
    used boolean NOT NULL
);


--
-- Name: password_reset_tokens_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.password_reset_tokens ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.password_reset_tokens_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: streaks; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.streaks (
    id bigint NOT NULL,
    current_streak integer NOT NULL,
    longest_streak integer NOT NULL,
    updated_at timestamp(6) without time zone,
    circle_id bigint NOT NULL,
    user_id bigint NOT NULL,
    last_threshold_date date
);


--
-- Name: streaks_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.streaks ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.streaks_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: task_checkins; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.task_checkins (
    id bigint NOT NULL,
    checkin_date date NOT NULL,
    completed boolean NOT NULL,
    created_at timestamp(6) without time zone,
    task_id bigint NOT NULL,
    user_id bigint NOT NULL
);


--
-- Name: task_checkins_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.task_checkins ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.task_checkins_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: users; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.users (
    id bigint NOT NULL,
    created_at timestamp(6) without time zone,
    email character varying(255) NOT NULL,
    password character varying(255) NOT NULL,
    username character varying(255) NOT NULL,
    is_admin boolean DEFAULT false,
    is_verified boolean DEFAULT false NOT NULL
);


--
-- Name: users_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.users ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.users_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: badges badges_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.badges
    ADD CONSTRAINT badges_pkey PRIMARY KEY (id);


--
-- Name: checkins checkins_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.checkins
    ADD CONSTRAINT checkins_pkey PRIMARY KEY (id);


--
-- Name: circle_members circle_members_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.circle_members
    ADD CONSTRAINT circle_members_pkey PRIMARY KEY (id);


--
-- Name: circle_tasks circle_tasks_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.circle_tasks
    ADD CONSTRAINT circle_tasks_pkey PRIMARY KEY (id);


--
-- Name: circles circles_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.circles
    ADD CONSTRAINT circles_pkey PRIMARY KEY (id);


--
-- Name: email_verification_tokens email_verification_tokens_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.email_verification_tokens
    ADD CONSTRAINT email_verification_tokens_pkey PRIMARY KEY (id);


--
-- Name: goals goals_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.goals
    ADD CONSTRAINT goals_pkey PRIMARY KEY (id);


--
-- Name: password_reset_tokens password_reset_tokens_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.password_reset_tokens
    ADD CONSTRAINT password_reset_tokens_pkey PRIMARY KEY (id);


--
-- Name: streaks streaks_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.streaks
    ADD CONSTRAINT streaks_pkey PRIMARY KEY (id);


--
-- Name: task_checkins task_checkins_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.task_checkins
    ADD CONSTRAINT task_checkins_pkey PRIMARY KEY (id);


--
-- Name: users uk6dotkott2kjsp8vw4d0m25fb7; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.users
    ADD CONSTRAINT uk6dotkott2kjsp8vw4d0m25fb7 UNIQUE (email);


--
-- Name: password_reset_tokens uk71lqwbwtklmljk3qlsugr1mig; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.password_reset_tokens
    ADD CONSTRAINT uk71lqwbwtklmljk3qlsugr1mig UNIQUE (token);


--
-- Name: email_verification_tokens ukewmvysc7e9y6uy7og2c21axa9; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.email_verification_tokens
    ADD CONSTRAINT ukewmvysc7e9y6uy7og2c21axa9 UNIQUE (token);


--
-- Name: checkins ukfbfnm482ea1bwf8604ggpxsb3; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.checkins
    ADD CONSTRAINT ukfbfnm482ea1bwf8604ggpxsb3 UNIQUE (user_id, circle_id, checkin_date);


--
-- Name: task_checkins ukhn1xsxk6s0iyypd46mfq8gorg; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.task_checkins
    ADD CONSTRAINT ukhn1xsxk6s0iyypd46mfq8gorg UNIQUE (task_id, user_id, checkin_date);


--
-- Name: circles ukqtfaxuvldcfkgjvg5otms9876; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.circles
    ADD CONSTRAINT ukqtfaxuvldcfkgjvg5otms9876 UNIQUE (invite_code);


--
-- Name: users ukr43af9ap4edm43mmtq01oddj6; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.users
    ADD CONSTRAINT ukr43af9ap4edm43mmtq01oddj6 UNIQUE (username);


--
-- Name: streaks ukriabuma5gfnm87t6njok8rx1q; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.streaks
    ADD CONSTRAINT ukriabuma5gfnm87t6njok8rx1q UNIQUE (user_id, circle_id);


--
-- Name: users users_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.users
    ADD CONSTRAINT users_pkey PRIMARY KEY (id);


--
-- Name: goals fk4u3v8ue5s5h6hj6oe9jitvxy0; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.goals
    ADD CONSTRAINT fk4u3v8ue5s5h6hj6oe9jitvxy0 FOREIGN KEY (circle_id) REFERENCES public.circles(id);


--
-- Name: badges fk6xty094p6yob3kcweag7yv6c8; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.badges
    ADD CONSTRAINT fk6xty094p6yob3kcweag7yv6c8 FOREIGN KEY (user_id) REFERENCES public.users(id);


--
-- Name: checkins fk81gcnk1emrj19gv3x67u4f8bx; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.checkins
    ADD CONSTRAINT fk81gcnk1emrj19gv3x67u4f8bx FOREIGN KEY (user_id) REFERENCES public.users(id);


--
-- Name: task_checkins fkdk5581afje8ll9ad1tx7bixwv; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.task_checkins
    ADD CONSTRAINT fkdk5581afje8ll9ad1tx7bixwv FOREIGN KEY (task_id) REFERENCES public.circle_tasks(id);


--
-- Name: circle_members fkebqlug5f78ojop2j7qnbg4y15; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.circle_members
    ADD CONSTRAINT fkebqlug5f78ojop2j7qnbg4y15 FOREIGN KEY (user_id) REFERENCES public.users(id);


--
-- Name: circles fkf540o0jl12bafgjkfksr91cuq; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.circles
    ADD CONSTRAINT fkf540o0jl12bafgjkfksr91cuq FOREIGN KEY (created_by) REFERENCES public.users(id);


--
-- Name: task_checkins fkh5f2w6uqfqghff1xi2prgkous; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.task_checkins
    ADD CONSTRAINT fkh5f2w6uqfqghff1xi2prgkous FOREIGN KEY (user_id) REFERENCES public.users(id);


--
-- Name: circle_tasks fkhe2wt46w447ucyx9tqnvpp4n4; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.circle_tasks
    ADD CONSTRAINT fkhe2wt46w447ucyx9tqnvpp4n4 FOREIGN KEY (circle_id) REFERENCES public.circles(id);


--
-- Name: streaks fkmk6t6bsujyp3m0p9aigwiciwy; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.streaks
    ADD CONSTRAINT fkmk6t6bsujyp3m0p9aigwiciwy FOREIGN KEY (user_id) REFERENCES public.users(id);


--
-- Name: badges fkn3mosl60rum4ic9smg7nm0fff; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.badges
    ADD CONSTRAINT fkn3mosl60rum4ic9smg7nm0fff FOREIGN KEY (circle_id) REFERENCES public.circles(id);


--
-- Name: checkins fkomxdusw7ggaq3g81wr3mn06g8; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.checkins
    ADD CONSTRAINT fkomxdusw7ggaq3g81wr3mn06g8 FOREIGN KEY (circle_id) REFERENCES public.circles(id);


--
-- Name: circle_members fkowcca54fhuvsh1xgnorhl4lfq; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.circle_members
    ADD CONSTRAINT fkowcca54fhuvsh1xgnorhl4lfq FOREIGN KEY (circle_id) REFERENCES public.circles(id);


--
-- Name: streaks fkreqebsovw6urshjulb1d04dnr; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.streaks
    ADD CONSTRAINT fkreqebsovw6urshjulb1d04dnr FOREIGN KEY (circle_id) REFERENCES public.circles(id);


--
-- Name: circle_tasks fktadaot273am130ko9muhsu178; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.circle_tasks
    ADD CONSTRAINT fktadaot273am130ko9muhsu178 FOREIGN KEY (user_id) REFERENCES public.users(id);


--
-- PostgreSQL database dump complete
--

\unrestrict 2716qWRxioBolQu3E3gTMSm0kBzjLiRhWXfOmbPHBjnYUcT2ilzW9OLEleXLZNl

